version = 0.1
[default.deploy.parameters]
stack_name = "chessaginev_"
resolve_s3 = true
s3_prefix = "chessaginev_"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = ""
image_repositories = []
